### PR TITLE
Fixup javadoc errors and add doc gen to CI.

### PR DESCRIPTION
**Pull request by jsirois**

### CODE REVIEW

**Comment by jsirois** [comment]
Found this trying to publish - which generates javadoc.

Over to you @gmalmquist  for review and patch in.

FWIW - I patch in like so: `curl -L https://github.com/pantsbuild/jarjar/pull/12.patch | git am -3`

**Comment by gmalmquist** [comment]
LGTM

**Comment by jsirois** [comment]
Patched in @ https://github.com/pantsbuild/jarjar/commit/cc699dec37eacb7afd00e841322c3ee504510ccc

**Pull request closed without merging**
