### PR TITLE
Upgrade pants to 1.9.0.

### PR DESCRIPTION
**Pull request by jsirois**

### CODE REVIEW

**Review by stuhood — APPROVED** [review]
Thanks!

**Comment by jsirois** [comment]
Hrm, may not be able to do this upgrade easily. Pants still claims support for JDK 7 and here we're failing a JDK 7 shard (no clue why not both and why not JDK6) on a java 8 classfile from xsbti. So it looks like we'd need to downgrade the zinc Pants 1.9.0 is using and this may not be possible. All in all, more trouble than its worth for me at the moment since the build is working just fine as is.

**Comment by jsirois** [comment]
Likely related to https://github.com/pantsbuild/pants/issues/4380

**Comment by stuhood** [comment]
Hm, I think that "targeting" a JDK vs actually compiling with are different situations here. zinc might need to run under 8+, but if you have both 7 and 8 installed, we should be able to target 7.

It's very possible that there are gaps in these tests though: https://github.com/pantsbuild/pants/blob/master/tests/python/pants_test/backend/jvm/tasks/jvm_compile/java/test_java_compile_integration.py#L57 ...

**Pull request closed without merging**
